# (C) Copyright 2024-2026 Dassault Systemes SE.  All Rights Reserved.

server {
  listen 84;

  absolute_redirect off;

  location /ui/ {
    proxy_pass http://localhost:3000/ui/;
  }

  location /ui/theme/custom.json {
    alias /usr/share/nginx/html/theme/custom.json;
  }

  location /cas-server/ {
    proxy_pass http://localhost/cas-server/;
  }

  location /keycloak/ {
    proxy_pass http://localhost/keycloak/;
  }

  location /ui/config.json {
    alias /usr/share/nginx/html/static/config.json;
  }

  location /ui/multiinstance.json {
    proxy_pass http://localhost/ui/multiinstance.json;
  }

  location /ui-instances/ {
    proxy_pass http://localhost/ui-instances/;
  }

  location /static {
    alias /usr/share/nginx/html/static;
  }

  location /api1/ {
    proxy_pass http://localhost/api/;
  }

  location /api2/ {
    proxy_pass http://localhost/api/;
  }

  location /nuodb-cp/ {
    proxy_pass http://localhost/api/;
  }

  location /nuodb-cp/events {
    proxy_pass http://localhost/api/events;
    proxy_buffering off;
  }

  location /api/sql/ {
    proxy_pass http://localhost/api/sql/;
    proxy_buffering off;
    client_max_body_size 1024g;
  }

  location /api/ws/sql/ {
    proxy_pass http://localhost/api/ws/sql/;
    proxy_buffering off;
  }

  location / {
    proxy_pass http://localhost:3000/;
  }
}
