apiVersion: cp.nuodb.com/v1beta1
kind: HelmFeature
metadata:
  name: nano-resources
spec:
  values:
    admin:
      resources:
        limits:
          cpu: 500m
          memory: 500Mi
        requests:
          cpu: 500m
          memory: 500Mi
    database:
      sm:
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 500m
            memory: 500Mi
        memoryOption: 500Mi
      te:
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 500m
            memory: 500Mi
        memoryOption: 500Mi

---
apiVersion: cp.nuodb.com/v1beta1
kind: HelmFeature
metadata:
  name: nano-disk
spec:
  values:
    admin:
      persistence:
        enabled: true
        size: 1Gi
    database:
      persistence:
        enabled: true
        size: 5Gi

---
apiVersion: cp.nuodb.com/v1beta1
kind: HelmFeature
metadata:
  name: small-resources
spec:
  values:
    admin:
      resources:
        limits:
          cpu: "1"
          memory: 1Gi
        requests:
          cpu: "1"
          memory: 1Gi
    database:
      sm:
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: "1"
            memory: 2Gi
        memoryOption: 2Gi
      te:
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: "1"
            memory: 2Gi
        memoryOption: 2Gi

---
apiVersion: cp.nuodb.com/v1beta1
kind: HelmFeature
metadata:
  name: small-disk
spec:
  values:
    admin:
      persistence:
        enabled: true
        size: 1Gi
    database:
      persistence:
        enabled: true
        size: 20Gi

---
apiVersion: cp.nuodb.com/v1beta1
kind: HelmFeature
metadata:
  name: io1-disk
spec:
  values:
    database:
      persistence:
        storageClass: io1

---
apiVersion: cp.nuodb.com/v1beta1
kind: HelmFeature
metadata:
  name: n0-replicas
spec:
  parameters:
    teReplicas:
      default: "1"
      jsonSchema: |-
        {
          "type": "integer",
          "minimum": 0
        }
  values:
    admin:
      replicas: 1
    database:
      sm:
        hotCopy:
          enablePod: false
        noHotCopy:
          replicas: 1
      te:
        replicas: << .meta.params.teReplicas >>

---
apiVersion: cp.nuodb.com/v1beta1
kind: HelmFeature
metadata:
  name: n1-replicas
spec:
  parameters:
    teReplicas:
      default: "2"
      jsonSchema: |-
        {
          "type": "integer",
          "minimum": 0
        }
  values:
    admin:
      replicas: 3
    database:
      sm:
        hotCopy:
          enablePod: false
        noHotCopy:
          replicas: 2
      te:
        replicas: << .meta.params.teReplicas >>

---
apiVersion: cp.nuodb.com/v1beta1
kind: HelmFeature
metadata:
  name: kube-inspector
spec:
  values:
    nuodb:
      serviceAccount: serviceaccount

---
apiVersion: cp.nuodb.com/v1beta1
kind: HelmFeature
metadata:
  name: ephemeral-volume
spec:
  chartCompatibility: ">=3.6.0"
  optional: true
  values:
    admin:
      ephemeralVolume:
        enabled: true
    database:
      ephemeralVolume:
        enabled: true

---
apiVersion: cp.nuodb.com/v1beta1
kind: HelmFeature
metadata:
  name: enhanced-security
spec:
  chartCompatibility: ">=3.6.0"
  productCompatibility: ">=4.3.3"
  optional: true
  values:
    admin:
      initContainers:
        runInitDisk: false
      securityContext:
        runAsNonRootGroup: true
        enabledOnContainer: true
        privileged: false
        allowPrivilegeEscalation: false
        capabilities:
          drop:
          - ALL
          add:
          - SYS_PTRACE
        readOnlyRootFilesystem: true
    database:
      initContainers:
        runInitDisk: false
      securityContext:
        runAsNonRootGroup: true
        enabledOnContainer: true
        privileged: false
        allowPrivilegeEscalation: false
        capabilities:
          drop:
          - ALL
          add:
          - SYS_PTRACE
        readOnlyRootFilesystem: true

---
apiVersion: cp.nuodb.com/v1beta1
kind: HelmFeature
metadata:
  name: archive-sync-workaround
spec:
  productCompatibility: ">=5.0, <5.0.3"
  optional: true
  values:
    database:
      sm:
        engineOptions:
          bulk-archive-sync: disable

---
apiVersion: cp.nuodb.com/v1beta1
kind: HelmFeature
metadata:
  name: ssl-passthrough
spec:
  values:
    admin:
      ingress:
        sql:
          annotations:
            ingress.kubernetes.io/ssl-passthrough: "true"
            nginx.ingress.kubernetes.io/ssl-passthrough: "true"
            haproxy.org/ssl-passthrough: "true"
    database:
      te:
        ingress:
          annotations:
            ingress.kubernetes.io/ssl-passthrough: "true"
            nginx.ingress.kubernetes.io/ssl-passthrough: "true"
            haproxy.org/ssl-passthrough: "true"

---
apiVersion: cp.nuodb.com/v1beta1
kind: HelmFeature
metadata:
  name: backup-hooks
spec:
  chartCompatibility: ">=3.8.0"
  optional: true
  values:
    database:
      backupHooks:
        enabled: "true"
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi

---
apiVersion: cp.nuodb.com/v1beta1
kind: HelmFeature
metadata:
  name: backup-hooks-fsfreeze
spec:
  chartCompatibility: ">=3.9.0"
  productCompatibility: "<6.0.2"
  optional: true
  values:
    database:
      backupHooks:
        freezeMode: fsfreeze

---
apiVersion: cp.nuodb.com/v1beta1
kind: HelmFeature
metadata:
  name: backup-hooks-hotsnap
spec:
  chartCompatibility: ">=3.9.0"
  productCompatibility: ">=6.0.2"
  optional: true
  values:
    database:
      backupHooks:
        freezeMode: hotsnap

---
apiVersion: cp.nuodb.com/v1beta1
kind: ServiceTier
metadata:
  name: n0.nano
  annotations:
    description: |-
      An entry type NuoDB service for evaluation purposes with minimal viable \
      specification and general purpose disks. The database will be started with 1 \
      Storage Manager and 1 Transaction Engine.
spec:
  features:
  - name: nano-resources
  - name: nano-disk
  - name: n0-replicas
  - name: kube-inspector
  - name: archive-sync-workaround
  - name: ssl-passthrough
  - name: backup-hooks-fsfreeze
  - name: backup-hooks-hotsnap

---
apiVersion: cp.nuodb.com/v1beta1
kind: ServiceTier
metadata:
  name: n0.small
  annotations:
    description: |-
      An entry type NuoDB service for evaluation purposes with 2G memory, 20G storage \
      and general purpose disks. The database will be started with 1 Storage Manager \
      and 1 Transaction Engine.
spec:
  features:
  - name: small-resources
  - name: small-disk
  - name: n0-replicas
  - name: kube-inspector
  - name: archive-sync-workaround
  - name: ssl-passthrough
  - name: backup-hooks-fsfreeze
  - name: backup-hooks-hotsnap

---
apiVersion: cp.nuodb.com/v1beta1
kind: ServiceTier
metadata:
  name: n1.small
  annotations:
    description: |-
      A general-purpose NuoDB service resilient to failures with 1 vCPU, 2G memory, \
      20G storage and SSD disks. The database will be started with 2 Storage Managers \
      and 2 Transaction Engines.
spec:
  features:
  - name: small-resources
  - name: small-disk
  - name: io1-disk
  - name: n1-replicas
  - name: kube-inspector
  - name: archive-sync-workaround
  - name: ssl-passthrough
  - name: backup-hooks-fsfreeze
  - name: backup-hooks-hotsnap
