# (C) Copyright 2024 Dassault Systemes SE.  All Rights Reserved.

services:
  selenium:
    image: "selenium/standalone-chrome"
    shm_size: '2gb'
    ports:
      - "4444:4444"
      - "7900:7900"
    depends_on:
      - nginx
    networks:
      - kwok-kwok
    environment:
      - SE_VNC_NO_PASSWORD=true
    healthcheck:
      test: curl --fail http://selenium:4444/ || exit 1
      interval: 5s
      timeout: 30s
      retries: 3
      start_period: 60s
  nuodbaas-webui:
    image: "nuodbaas-webui"
    networks:
      - kwok-kwok
    healthcheck:
      test: curl --fail http://nuodbaas-webui:8080/ || exit 1
      interval: 5s
      timeout: 30s
      retries: 3
      start_period: 60s
  nuodb-cp:
    image: "ghcr.io/nuodb/nuodb-cp-images:2.7.0"
    ports:
      - "8081:8080"
    command:
      - "rest-service"
    networks:
      - kwok-kwok
    volumes:
      - ./files/kubeconfig:/home/nuodb/.kube/config
    healthcheck:
      test: curl --fail http://nuodb-cp:8080/healthz
      interval: 5s
      timeout: 30s
      retries: 3
      start_period: 60s
  nuodb-cp-operator:
    image: "ghcr.io/nuodb/nuodb-cp-images:2.7.0"
    command:
      - "controller"
      - "--feature-gates"
      - "EmbeddedDatabaseBackupPlugin=false"
    networks:
      - kwok-kwok
    volumes:
      - ./files/kubeconfig:/home/nuodb/.kube/config
    environment:
      ENABLE_WEBHOOKS: "false"
  nginx:
    image: "nginx"
    ports:
      - "8088:80"
    networks:
      - kwok-kwok
    volumes:
      - ./files/nginx-default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - nuodbaas-webui
      - nuodb-cp
    healthcheck:
      test: curl --fail http://nginx/ || exit 1
      interval: 5s
      timeout: 30s
      retries: 3
      start_period: 60s
networks:
  kwok-kwok:
    name: kwok-kwok
    external: true
