services:
  selenium:
    image: "selenium/standalone-chrome"
    ports:
      - "4444:4444"
      - "7900:7900"
    depends_on:
      - nginx
    networks:
      - kwok-kwok
    healthcheck:
      test: curl --fail http://selenium:4444/ || exit 1
      interval: 40s
      timeout: 30s
      retries: 3
      start_period: 60s
  dbaas-cockpit:
    image: "dbaas-cockpit"
    ports:
      - "8081:80"
    networks:
      - kwok-kwok
    healthcheck:
      test: curl --fail http://dbaas-cockpit/ || exit 1
      interval: 40s
      timeout: 30s
      retries: 3
      start_period: 60s
  nuodb-cp:
    image: "ghcr.io/nuodb/nuodb-cp-images:2.6.0"
    ports:
      - "8082:8080"
    command:
      - "rest-service"
    networks:
      - kwok-kwok
    volumes:
      - ./files/kubeconfig:/home/nuodb/.kube/config
    healthcheck:
      test: curl --fail http://nuodb-cp:8080/healthz
      interval: 40s
      timeout: 30s
      retries: 3
      start_period: 60s
  nginx:
    image: "nginx"
    ports:
      - "8080:80"
    networks:
      - kwok-kwok
    volumes:
      - ./files/nginx-default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - dbaas-cockpit
      - nuodb-cp
    healthcheck:
      test: curl --fail http://nginx/ || exit 1
      interval: 40s
      timeout: 30s
      retries: 3
      start_period: 60s
networks:
  kwok-kwok:
    name: kwok-kwok
    external: true
