# (C) Copyright 2024-2025 Dassault Systemes SE.  All Rights Reserved.

services:
  selenium:
    image: "selenium/standalone-chrome:131.0"
    shm_size: '2gb'
    depends_on:
      - nginx
    network_mode: host
    environment:
      - SE_VNC_NO_PASSWORD=true
    healthcheck:
      test: curl --fail http://localhost:4444/
      interval: 5s
      timeout: 30s
      retries: 3
      start_period: 60s
  nginx:
    image: "nginx"
    network_mode: host
    volumes:
      - ./files/nginx-default.conf:/etc/nginx/conf.d/default.conf
    healthcheck:
      test: curl --fail http://localhost:81/
      interval: 5s
      timeout: 30s
      retries: 3
      start_period: 60s
networks:
  kind:
    name: kind
    external: true
