# (C) Copyright 2026 Dassault Systemes SE.  All Rights Reserved.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium
  labels:
    app.kubernetes.io/name: selenium
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: selenium
  template:
    metadata:
      labels:
        app.kubernetes.io/name: selenium
    spec:
      containers:
      - name: selenium
        image: "selenium/standalone-chrome"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 4444
        - containerPort: 7900
        env:
        - name: SE_VNC_NO_PASSWORD
          value: "true"
        - name: SE_SUB_PATH
          value: "/selenium"
        volumeMounts:
        - mountPath: /dev/shm
          name: dshm
        livenessProbe:
          httpGet:
            path: /
            port: 4444
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 4444
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
          sizeLimit: "2Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: selenium
spec:
  selector:
    app.kubernetes.io/name: selenium
  ports:
    - name: port-4444
      protocol: TCP
      port: 4444
      targetPort: 4444
    - name: port-7900
      protocol: TCP
      port: 7900
      targetPort: 7900
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: selenium
  labels:
    app.kubernetes.io/name: selenium
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /selenium(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: selenium
                port:
                  number: 4444
          - path: /selenium-vnc(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: selenium
                port:
                  number: 7900
