# (C) Copyright 2024 Dassault Systemes SE.  All Rights Reserved.

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{- include "dbaas-cockpit.labels" . | nindent 4 }}
spec:
  rules:
    - http:
        paths:
          - path: "/{{ .Values.dbaasCockpit.ingress.pathPrefix }}"
            pathType: Prefix
            backend:
              service:
                name: {{ $.Chart.Name }}
                port:
                  number: 8080
    {{- range .Values.dbaasCockpit.ingress.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          - path: "/{{ $.Values.dbaasCockpit.ingress.pathPrefix }}"
            pathType: Prefix
            backend:
              service:
                name: {{ $.Chart.Name }}
                port:
                  number: 8080
    {{- end }}
