apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{- include "dbaas-cockpit.labels" . | nindent 4 }}
spec:
  rules:
    - http:
        paths:
          - path: "/{{ .Values.dbaasCockpit.pathPrefix }}"
            pathType: Prefix
            backend:
              service:
                name: {{ .Chart.Name }}
                port:
                  number: 80
