# (C) Copyright 2024 Dassault Systemes SE.  All Rights Reserved.

apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{- include "dbaas-cockpit.labels" . | nindent 4 }}
spec:
  type: {{ .Values.dbaasCockpit.service.type }}
  ports:
    - port: 8080
      targetPort: http-alt
      protocol: TCP
      name: http-alt
  selector:
    {{- include "dbaas-cockpit.selectorLabels" . | nindent 4 }}
