# (C) Copyright 2026 Dassault Systemes SE.  All Rights Reserved.

apiVersion: cp.nuodb.com/v1beta1
kind: IdentityProvider
metadata:
  annotations:
    description: CAS Keycloak
  name: cas-keycloak
spec:
  cas:
    serverUrl: http://ingress-nginx-controller.ingress-nginx.svc.cluster.local/keycloak/realms/test/protocol/cas
  provisionUser:
    accessRule:
      value: |
        {"allow": ["read:acme"]}
    name:
      jsonPath: $.user
    organization:
      value: acme
---
apiVersion: cp.nuodb.com/v1beta1
kind: IdentityProvider
metadata:
  annotations:
    description: CAS Simple
  name: cas-simple
spec:
  cas:
    serverUrl: http://ingress-nginx-controller.ingress-nginx.svc.cluster.local/cas-server
  provisionUser:
    accessRule:
      value: |
        {"allow": ["read:acme"]}
    name:
      jsonPath: $.user
    organization:
      value: acme
