# (C) Copyright 2024 Dassault Systemes SE.  All Rights Reserved.

# Default values for nuodbaas-webui.
nuodbaasWebui:
  replicaCount: 1
  image:
    repository: ghcr.io/nuodb/nuodbaas-webui
    pullPolicy: IfNotPresent
    pullSecrets: []
    tag: ""
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  service:
    type: ClusterIP
  ingress:
    pathPrefix: ui
    hosts:
      - nuodbaas-webui.local
    className: ""
  cpUrl: /nuodb-cp
