{{- if .Values.nuodbaasWebui.autoscaling.enabled }}
apiVersion: {{ include "hpa.apiVersion" . }}
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "nuodbaas-webui.fullname" . }}
  labels:
    {{- include "nuodbaas-webui.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "nuodbaas-webui.fullname" . }}
  minReplicas: {{ .Values.nuodbaasWebui.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.nuodbaasWebui.autoscaling.maxReplicas }}
  metrics:
    {{- include "hpa.targetAverageUtilization" . | nindent 4 }}
{{- end }}
