{{- if .Values.nuodbaasWebui.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "nuodbaas-webui.fullname" . }}
  labels:
    {{- include "nuodbaas-webui.labels" . | nindent 4 }}
spec:
  egress:
  - {}
  ingress:
    - ports:
      - protocol: TCP
        port: {{ .Values.nuodbaasWebui.service.port }}
  podSelector:
    matchLabels:
      {{- include "nuodbaas-webui.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  - Egress
{{- end }}