# (C) Copyright 2026 Dassault Systemes SE.  All Rights Reserved.
{{- if .Values.nuodbaasWebui.multiInstancePassword }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "nuodbaas-webui-multi-instance"
type: Opaque
stringData:
  "username": {{ .Values.nuodbaasWebui.multiInstanceUsername | quote }}
  "password": {{ .Values.nuodbaasWebui.multiInstancePassword | quote }}
{{- end }}
