apiVersion: v1
kind: Service
metadata:
  name: {{ include "nuodbaas-webui.fullname" . }}
  labels:
    {{- include "nuodbaas-webui.labels" . | nindent 4 }}
spec:
  type: {{ .Values.nuodbaasWebui.service.type }}
  ports:
    - port: {{ .Values.nuodbaasWebui.service.port }}
      targetPort: http-alt
      protocol: TCP
      name: http-alt
  selector:
    {{- include "nuodbaas-webui.selectorLabels" . | nindent 4 }}
