# (C) Copyright 2024-2025 Dassault Systemes SE.  All Rights Reserved.
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nuodbaas-webui.fullname" . }}
  {{- with .Values.nuodbaasWebui.service.annotations }}
  annotations:
    {{- include "nuodbaas-webui.toYaml" (list $ .) | nindent 4 }}
  {{- end }}
  labels:
    {{- include "nuodbaas-webui.labels" . | nindent 4 }}
spec:
  type: {{ .Values.nuodbaasWebui.service.type }}
  ports:
    - port: {{ .Values.nuodbaasWebui.service.port }}
      targetPort: http-alt
      protocol: TCP
      name: http-alt
  selector:
    {{- include "nuodbaas-webui.selectorLabels" . | nindent 4 }}
