# Default values for dbaas-cockpit.
dbaasCockpit:
  replicaCount: 1
  image:
    repository: 253548315642.dkr.ecr.us-east-1.amazonaws.com/dbaas-cockpit-docker
    pullPolicy: IfNotPresent
    pullSecrets: []
    tag: ""
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  service:
    type: ClusterIP
  ingress:
    pathPrefix: ui
    hosts:
      - dbaas-cockpit.local
  cpUrl: /nuodb-cp
