name: Build
on:
  push:
    branches:
      - "main"
      - "rel/*"
jobs:
  publish_docker_image:
    name: Publish Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Build Image
        run: |
          make build-image
      - name: Setup Integration Test Environment
        run: |
          make setup-integration-tests
      - name: Run Integration Tests
        run: |
          make run-integration-tests-only
      - name: Teardown Integration Test Environment
        if: !cancelled()
        run: |
          make teardown-integration-tests
      - name: 'Login to GHCR'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Deploy Docker image to GHCR
        run: |
          ./build_utils.sh uploadDockerImage
      - name: Upload Test Results
        if: !cancelled()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: selenium-tests/target/test-results
          retention-days: 7

  publish_helm_chart:
    name: Publish Helm Chart
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Install Helm
        uses: azure/setup-helm@v4
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - name: Create Helm Package
        run: |
          ./build_utils.sh createHelmPackage
      - name: Upload package to Helm Index
        run: |
          ./build_utils.sh uploadHelmPackage
